export const colors = {
  primary: '#4A4AFF',
  secondary: '#2D56B6',
  tertiary: '#F0A225',
  success: '#2FD36F',
  warning: '#FDC40C',
  danger: '#EC445A',
  white: '#FFFFFF',
  light: '#EBEBEB',
  dark: '#222428',
  black: '#000000',
  headerBg: '',
  headerFont: '',
  footerBg: '',
  footerFont: '',
} as const;