require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Include the .xcworkspace extension
workspace 'LAReactNative.xcworkspace'

target 'LAReactNative' do
  config = use_native_modules!

  # Explicitly configure RCT-Folly
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec', :modular_headers => true
  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'BEMCheckBox'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'LAReactNativeTests' do
    inherit! :complete
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Basic settings
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'

        # Add header search paths
        config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/React-Core ${PODS_ROOT}/Headers/Public/React-Codegen ${PODS_ROOT}/Headers/Public/ReactCommon ${PODS_ROOT}/Headers/Public/React'
        
        # React-specific settings
        if target.name == 'React-Core'
          config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_TARGET_SRCROOT}/ReactCommon ${PODS_TARGET_SRCROOT} ${PODS_ROOT}/Headers/Private/React-Core'
        end

        # Folly settings
        if target.name.include?('RCT-Folly')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_HAVE_COROUTINES=0'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_HAVE_COROUTINES=0'
        else
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1'
        end

        # Reanimated settings
        if target.name.include?('react-native-reanimated')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'REANIMATED_VERSION_STRING=\"3.1.0\"'
        end
      end
    end
  
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
